// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1N_60GKPsHWnUDQXzTzjar3UnFd7K1jU',
    appId: '1:374164356163:web:5ffa0da1ae065f90fba8f6',
    messagingSenderId: '374164356163',
    projectId: 'nordisk-mashscore',
    authDomain: 'nordisk-mashscore.firebaseapp.com',
    storageBucket: 'nordisk-mashscore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGvT9-HYDOfh2xlRwfJOfL-N-GlJLicgo',
    appId: '1:374164356163:android:69df8bfce7f02609fba8f6',
    messagingSenderId: '374164356163',
    projectId: 'nordisk-mashscore',
    storageBucket: 'nordisk-mashscore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgWwRa1l75_PIVJEJG5D_apON761vLE0',
    appId: '1:374164356163:ios:309cfc010497c964fba8f6',
    messagingSenderId: '374164356163',
    projectId: 'nordisk-mashscore',
    storageBucket: 'nordisk-mashscore.firebasestorage.app',
    iosBundleId: 'com.nordisk.nordisk',
  );
}
